services:
  ai-separation-app:
    build: .
    container_name: ai-separation-app
    environment:
      # Clés API / secrets
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Base de données
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # Chemins des images dans le conteneur
      NAS_BASE: /hdd1
      IMAGE_BASE: /hdd1
      IMAGE_COMPTABILISEE_BASE: /hdd1/images/images
      IMAGE_A_TRAITER: /hdd1/images/images
    volumes:
      - "./.env:/app/.env"
      - "/hdd1:/hdd1:z"

    # Décommente si ton script démarre une API (FastAPI, Flask, etc.)
    # ports:
    #   - "8000:8000"

    # Redémarre automatiquement sauf arrêt manuel
    restart: unless-stopped 

  ai-analyse:
    build: .
    container_name: ai-analyse-app

    command: python -u analyse.py
    environment:
      # Clés API / secrets
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Base de données
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # Chemins des images dans le conteneur
      NAS_BASE: /hdd1
      IMAGE_BASE: /hdd1
      IMAGE_COMPTABILISEE_BASE: /hdd1/images/images
      IMAGE_A_TRAITER: /hdd1/images/images
    volumes:
      - "./.env:/app/.env"
      - "/hdd1:/hdd1:z"

    # Décommente si ton script démarre une API (FastAPI, Flask, etc.)
    # ports:
    #   - "8000:8000"

    # Redémarre automatiquement sauf arrêt manuel
    restart: unless-stopped 

  ai-api:
    build: .
    container_name: ai-api-server
    # Override the CMD from the Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      # Clés API / secrets
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Base de données
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # Chemins des images dans le conteneur
      NAS_BASE: /hdd1
      IMAGE_BASE: /hdd1/images
      IMAGE_COMPTABILISEE_BASE: /hdd1/images/images
      IMAGE_A_TRAITER: /hdd1/images/images
    volumes:
      - "./.env:/app/.env"
      - "/hdd1:/hdd1:z"
    restart: unless-stopped